{
   "type": "record",
   "name": "input_schema.avsc",
   "fields": [
        {
            "name": "ID",
            "type": "int"
        },
        {
            "name": "NUMBER_PEOPLE_LIABLE",
            "type": "int"
        },
        {
            "name": "AGE_YEARS",
            "type": "int"
        },
        {
            "name": "PRESENT_EMPLOYMENT_SINCE",
            "type": "string"
        },
        {
            "name": "JOB",
            "type": "string"
        },
        {
            "name": "HOUSING",
            "type": "string"
        },
        {
            "name": "TELEPHONE",
            "type": "string"
        },
        {
            "name": "INSTALLMENT_PLANS",
            "type": "string"
        },
        {
            "name": "NUMBER_EXISTING_CREDITS",
            "type": "int"
        },
        {
            "name": "CREDIT_HISTORY",
            "type": "string"
        },
        {
            "name": "FOREIGN_WORKER",
            "type": "string"
        },
        {
            "name": "PROPERTY",
            "type": "string"
        },
        {
            "name": "INSTALLMENT_RATE",
            "type": "int"
        },
        {
            "name": "PURPOSE",
            "type": "string"
        },
        {
            "name": "CHECKING_STATUS",
            "type": "string"
        },
        {
            "name": "PRESENT_RESIDENCE_SINCE",
            "type": "int"
        },
        {
            "name": "DEBTORS_GUARANTORS",
            "type": "string"
        },
        {
            "name": "SAVINGS_ACCOUNT",
            "type": "string"
        },
        {
            "name": "DURATINO_MONTHS",
            "type": "int"
        },
        {
            "name": "CREDIT_AMOUNT",
            "type": "int"
        },
        {
            "name": "GENDER",
            "type": "string"
        },
        {
            "name": "LABEL",
            "type": "int"
        }
    ]
}
